<a href="https://colab.research.google.com/github/ChakritKammason/DPDM/blob/master/Data_103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
A = np.array([[1,2,3],[4,5,6]])

In [6]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
A.dot(A.T)

array([[14, 32],
       [32, 77]])

Array Slicing การตัด

In [11]:
A[0,1]

2

In [23]:
A[1,1:]

array([5, 6])

#สร้าง Distance Matrix (Eucidian) ของ data matrix ใน slides

In [27]:
data1 = np.array([[1,2],[3,5],[2,0],[4,5]])
data1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

สร้าง Manhuttan distance metrix

In [38]:
def manhuttan_dist(dp1,dp2):
  distx = abs(dp1[0]-dp2[0])
  disty = abs(dp1[1]-dp2[1])
  return distx + disty

สร้าง Array เปล่า

In [30]:
np.zeros((4,4)) #วิธีที่1 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
dist_mat_man = np.ones((4,4)) #วิธีที่2
dist_mat_man 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

เอาค่าที่คำนวณมาใส่

In [39]:
for i in range(4):
  for j in range(4):
    dist_mat_man[i,j] = manhuttan_dist(data1[i,:],data1[j,:])

dist_mat_man

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])