<a href="https://colab.research.google.com/github/ChakritKammason/DPDM/blob/master/Data_103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
A = np.array([[1,2,3],[4,5,6]])

In [4]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [6]:
A.dot(A.T)

array([[14, 32],
       [32, 77]])

Array Slicing การตัด

In [7]:
A[0,1]

2

In [8]:
A[1,1:]

array([5, 6])

#สร้าง Distance Matrix (Eucidian) ของ data matrix ใน slides

In [9]:
data1 = np.array([[1,2],[3,5],[2,0],[4,5]])
data1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

สร้าง Manhuttan distance metrix

In [10]:
def manhuttan_dist(dp1,dp2):
  distx = abs(dp1[0]-dp2[0])
  disty = abs(dp1[1]-dp2[1])
  return distx + disty

สร้าง Array เปล่า

In [11]:
np.zeros((4,4)) #วิธีที่1 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
dist_mat_man = np.ones((4,4)) #วิธีที่2
dist_mat_man 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

เอาค่าที่คำนวณมาใส่

In [13]:
for i in range(4):
  for j in range(4):
    dist_mat_man[i,j] = manhuttan_dist(data1[i,:],data1[j,:])

dist_mat_man

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

Eucidian

In [14]:
import math

In [26]:
def Euclidean_dist(ep1,ep2):
    dist_a = abs(ep1[0]-ep2[0])
    dist_b = abs(ep1[1]-ep2[1])
    return math.sqrt(dist_a**2 + dist_b**2)

In [27]:
dist_mat_Eu = np.zeros((4,4))

In [28]:
dist_mat_Eu

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
for i in range(4):
  for j in range(4):
      dist_mat_Eu[i,j] = Euclidean_dist(data1[i,:],data1[j,:])

dist_mat_Eu

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])