<a href="https://colab.research.google.com/github/ChakritKammason/DPDM/blob/master/Data_103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import math

In [ ]:
A = np.array([[1,2,3],[4,5,6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
A.dot(A.T)

array([[14, 32],
       [32, 77]])

Array Slicing การตัด

In [ ]:
A[0,1]

2

In [ ]:
A[1,1:]

array([5, 6])

#สร้าง Distance Matrix (Eucidian) ของ data matrix ใน slides

In [28]:
data11 = np.array([[1,2],[3,5],[2,0],[4,5]])
data11

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

สร้าง Manhuttan distance metrix

In [4]:
def manhuttan_dist(dp1,dp2):
  distx = abs(dp1[0]-dp2[0])
  disty = abs(dp1[1]-dp2[1])
  return distx + disty

สร้าง Array เปล่า

In [5]:
np.zeros((4,4)) #วิธีที่1 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
dist_mat_man = np.ones((4,4)) #วิธีที่2
dist_mat_man 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

เอาค่าที่คำนวณมาใส่

In [29]:
for i in range(4):
  for j in range(4):
    dist_mat_man[i,j] = manhuttan_dist(data11[i,:],data11[j,:])

dist_mat_man

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

Eucidian

In [8]:
def Euclidean_dist(ep1,ep2):
    dist_a = abs(ep1[0]-ep2[0])
    dist_b = abs(ep1[1]-ep2[1])
    return math.sqrt(dist_a**2 + dist_b**2)

In [9]:
dist_mat_Eu = np.zeros((4,4))

In [10]:
dist_mat_Eu

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
for i in range(4):
  for j in range(4):
      dist_mat_Eu[i,j] = Euclidean_dist(data11[i,:],data11[j,:])

dist_mat_Eu

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

# Distance of nominal or categorical features
(extra) Python data structure (Dictionary)


ตัวข้างหน้าคือ index ตัวข้างหลังคือ จะเก็บอะไร

In [17]:
d_A = {'a':1,2:3,3:5,'cat':6}
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [18]:
d_A['cat']

6

เพิ่มตค่าใน dictionary ชื่อ = ค่าที่จะเพิ่มเข้าไป

In [19]:
d_A['dog'] = [1,2,3,4,5]

In [20]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

สร้างตาราง Datafrema โดยใช้ pandas

In [22]:
import pandas as pd

In [24]:
data_dict = {'color':['red','red','green'],'status':['single','married','single']}
data_dict

{'color': ['red', 'red', 'green'], 'status': ['single', 'married', 'single']}

In [25]:
data_pd = pd.DataFrame.from_dict(data_dict)

In [26]:
data_pd

color   status
0    red   single
1    red  married
2  green   single

# Categorical feature distance method#1

[1,:] แถวที่ 1 ทุกหลัก

In [27]:
list(data_pd.iloc[1,:])

['red', 'married']

In [44]:
def meth1_dist(data1,data2):
  N = 0
  print(f'data is {data1} and data2 is {data2}')
  for i in range(len(data1)):
    if data1[i] != data2[i]:
      print(f'feature{i} of data1 is {data1[i]}, feature{i} of data2 is {data2[i]}')
      N = N + 1
      print(f' {data1[i]} is not equal {data2[i]} : update ({N})')
    else:
      print(f' {data1[i]} is equal {data2[i]} : update ({N})')
      
  return N/len(data1)

In [45]:
meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

data is ['red', 'single'] and data2 is ['red', 'married']
 red is equal red : update (0)
feature1 of data1 is single, feature1 of data2 is married
 single is not equal married : update (1)


0.5

# HW 7 calculate dustance matrix od data_pd using meth1_dist()
หา distance metrix